title: Rich Codes
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Matheus Richard, a Software Engineering from Brazil.
  I love open source, music, games and creating programming languages.
url: 'http://matheusrich.com' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog
paginate_path: '/page:num/'
permalink: /:title/
repo_url: https://github.com/MatheusRich/matheusrich.github.io

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-toc
paginate: 10

navigation:
  - title: ðŸ‘¨â€ðŸ’» About me
    url: /about/
  - title: ðŸ·ï¸ Categories
    url: /categories/
  - title: ðŸ“ All posts
    url: /all/
  - title: ðŸŽ™ï¸ Speaking
    url: /speaking/

social:
  twitter: matheusrich
  github: matheusrich
  linkedin: matheus-richard
  email: matheusrichardt@gmail.com

# google_analytics: "UA-58263416-1"

# Disqus Comments
# disqus:
#   shortname: matheusrich

talks:
  - title: Taming God Objects (ðŸ‡§ðŸ‡·)
    description: >
      Everyone has worked with an app with <strong>enormous classes</strong>, filled with mixed
      responsibilities. They're hard to understand, hard to change and hard to
      test. In this presentation we're gonna learn a refactoring technique to
      start taming those little monsters.
    date: 2021-01-27 -0300
    video_url: https://www.youtube.com/embed/fNZviKKU_lI?start=521
    slides_url: https://speakerdeck.com/matheusrich/taming-god-objects-easy-incremental-and-secure
  - title: 3 Steps Every Test Should Take â€” lightning talk (ðŸ‡§ðŸ‡·)
    description: >
      Good tests tell a story, and this story is made of 4 acts. In this talk I present a
      technique to make tests easy to read, write, and understand.
    date: 2021-07-28 -0300
    video_url: https://www.youtube.com/embed/c6PY_t17iPk?start=517
    slides_url: https://speakerdeck.com/matheusrich/3-steps-every-test-should-take
  - title: Start TDDing in 5 minutes â€” lightning talk (ðŸ‡§ðŸ‡·)
    description: >
      TDD is awesome, but can be scary. Learn how to start practicing it in 5 minutes by fixing bugs, so
      we can kill two birds with one stone!
    date: 2021-07-28 -0300
    slides_url: https://speakerdeck.com/matheusrich/start-tdding-in-5-minutes
    video_url: https://www.youtube.com/embed/c6PY_t17iPk?start=1695
  - title: Comments are the devil - Ruby Rogues Podcast
    description: >
      Inspired by the article <a href="/dont-use-comments-use-code/">Donâ€™t use comments! Use code</a>,
      I was invited to talk in the Ruby Rogues podcast about the dangers of comments.
    date: 2022-01-26 -0300
    audio_url: https://topenddevs.com/podcasts/ruby-rogues/episodes/comments-are-the-devil-ruby-532
  - title: "The Fast Lane: Async Ruby - Tropical.rb 2024"
    description: >
      Oh no! Computers are not doubling in speed every two years anymore! How can we make software run faster? You and your Rails app cannot just wait doing nothing, so join me to explore how we can leverage concurrency and parallelism concepts to enhance performance and scalability!
    date: 2024-04-05 -0300
    slides_url: https://docs.google.com/presentation/d/1zwy3RZhH4TOKBTEYPqtaK2Bl_d8bcIc9VhKr9t9lasw/view
    video_url: https://www.youtube.com/embed/CfC2blkrkys
  - title: "Ruby Internals: A Guide for Rails Developers - Tropical on Rails 2025"
    description: >
      Ever wondered how Ruby takes your code and runs it? Itâ€™s time to go on a journey into Ruby internals designed especially for Rails developers! Weâ€™ll learn about all the parts of an interpreter, and how their inner-workings affect our Rails apps! No experience with C is required!
    date: 2025-07-01 -0300
    slides_url: https://docs.google.com/presentation/d/1IdNgAU7z9umDeyx6xG8fv7wqauG3_QkfhpCM1sVXelw/view
    video_url: https://www.youtube.com/embed/nFoOmIpMcm0?si=pc5aRfuYPYMOMlJc
  - title: "How to get the most out of attending a conference - The Bike Shed #467"
    description: >
      JoÃ«l continues his preparations for the last RailsConf as he talks with Matheus about how to make the most of your time at the conference.

      Hear their tips to connect and communicate with other attendees, the different ways to take notes at the various talks you can attend, what to do when your discussions have a lull, as well as how to draw inspiration from others talks and using it to your advantage.
    date: 2022-01-26 -0300
    audio_url: https://bikeshed.thoughtbot.com/467
    embed: <iframe src="https://player.fireside.fm/v2/fa2C4vFU+NjlQNV0k?theme=dark" width="740" height="200" frameborder="0" scrolling="no"></iframe>
  - title: "Ruby Internals: A Guide for Rails Developers - RailsConf 2025"
    description: >
      Ever wondered how Ruby takes your code and runs it? Itâ€™s time to go on a journey into Ruby internals designed especially for Rails developers! Weâ€™ll learn about all the parts of an interpreter, and how their inner-workings affect our Rails apps! No experience with C is required!
    date: 2025-07-08 -0300
    event_url: https://railsconf.org/speakers/#matheus-richard
    slides_url: https://docs.google.com/presentation/d/1NZKbXAkYu_ynXfJ_u7avd-Viz9COX4a9yT9pQv1f4iw/view
    video_url: https://www.youtube.com/embed/ozayFBNKO2M
